### ISSUE TITLE
Error "Session has expired" in Weblogic using separate deployment

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#138]
Entered by Tambet Matiisen (tambetm):

After upgrading our application to use Orbeon 3.9 we have a problem - the form is shown, but after clicking on any form field the "Loading..." message is displayed and it stays there forever. Firebug shows, that all calls to /xforms-server get "500 Internal Server Error". Weblogic log shows error "Session has expired. Unable to process incoming request." The same setup works in Tomcat without a problem. Also Orbeon 3.8 works in that server without problems. Firebug shows, that cookies are sent to the application.

Our setup is as follows:
- WebLogic Server 10.3.2.0
- Orbeon 3.9.0 PE
- Separate deployment scheme with Orbeon deployed as /orbeon and our app as /orbeon-xtee.
- Orbeon deployed as ear, as suggested by documentation.
- Session cookie renamed to ORBEONSESSIOID in META-INF/weblogic-application.xml.

I traced the problem down to this commit:

https://github.com/orbeon/orbeon-forms/commit/5a5b6bb40917397f4db1ca3555a544bccd7af031

My suspect is, that Weblogic creates separate sessions for /orbeon and /orbeon-xtee contexts. The OrbeonXFormsFilter in /orbeon-xtee never calls httpRequest.getSession(true), so the session is never created for /orbeon-xtee, although it is later created for /orbeon.

Stack trace from Weblogic log:

```
####<May 23, 2011 2:20:00 PM EEST> <Error> <HTTP> <bea3a.arendus.kit>
<ORBEON-TEINE-A> <[ACTIVE] ExecuteThread: '0' for queue:
 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <> <1306149600818>
<BEA-101017> <[ServletContext@1818629160[app:te
ine-orbeon-xtee module:orbeon-xtee path:/orbeon-xtee spec-version:2.5]] Root
cause of ServletException.
javax.servlet.ServletException: Session has expired. Unable to process incoming
request.
        at org.orbeon.oxf.servlet.OrbeonXFormsFilter.doFilter(OrbeonXFormsFilter.java:76) 
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3592)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
        at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:121)
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2202)
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2108)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1432)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:201)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:173)
```

Moved from:

http://forge.ow2.org/tracker/index.php?func=detail&aid=315974&group_id=168&atid=350207

**Comment by ebruchez** [comment]
Separate deployment no longer supported, closing.
