### ISSUE TITLE
Proxy Portlet displays an error when the session times out

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2206]
If the Proxy Portlet is left sitting for about an hour it displays Orbeon's generic "An error has occurred" popup message. There is no error in the orbeon.log, but the Liferay console displays the errors below. The first line is repeated 10 times and the last line is repeated 263 times. It looks like it's because the Liferay session timed out. I wonder if the Proxy Portlet could handle this situation better.

    ERROR [org.orbeon.private.orbeon.embedding] Listing public parameters. Count: 0
    16:24:28,107 ERROR [RuntimePageImpl-3][IncludeTag:129] Current URL null generates exception: java.lang.IllegalStateException: Page needs a session and none is available
    java.lang.IllegalStateException: Page needs a session and none is available
        at org.apache.jasper.runtime.PageContextImpl._initialize(PageContextImpl.java:148)
        at org.apache.jasper.runtime.PageContextImpl.initialize(PageContextImpl.java:125)
        at org.apache.jasper.runtime.JspFactoryImpl.internalGetPageContext(JspFactoryImpl.java:112)
        at org.apache.jasper.runtime.JspFactoryImpl.getPageContext(JspFactoryImpl.java:65)
        at com.liferay.portal.kernel.servlet.JspFactoryWrapper.getPageContext(JspFactoryWrapper.java:63)
        at org.apache.jsp.html.common.themes.portlet_jsp._jspService(portlet_jsp.java:419)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:57)
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:78)
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
        at com.liferay.taglib.util.IncludeTag.include(IncludeTag.java:295)
        at com.liferay.taglib.util.IncludeTag.doInclude(IncludeTag.java:192)
        at com.liferay.taglib.util.IncludeTag.doEndTag(IncludeTag.java:83)
        at org.apache.jsp.html.portal.render_005fportlet_jsp._jspService(render_005fportlet_jsp.java:1624)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:57)
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:78)
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
    ERROR [org.orbeon.private.orbeon.embedding] Listing public parameters. Count: 0

**Comment by ebruchez** [comment]
It's curious that the stack trace doesn't show anything related to the proxy portlet though. You would imagine seeing at least one line in code belonging to the portlet.

Could it be instead that the session expires on the Form Runner side on the other end?

**Comment by wave2future** [comment]
Add following line at the beginning of your JSP files:
<%@ page session="false" %>

**Comment by ajw625** [comment]
@wave2future This is a portlet on a page in Liferay. There is no JSP.
