### ISSUE TITLE
JBoss 6 fails to parse web.xml

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2798]
Error:

```
17:44:19,892 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-4) MSC000001: Failed to start service jboss.deployment.unit."gate_three-orbeon-2.0.war".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."gate_three-orbeon-2.0.war".PARSE: JBAS018733: Failed to process phase PARSE of deployment "gate_three-orbeon-2.0.war"
at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:166) [jboss-as-server-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_73]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java) [rt.jar:1.8.0_73]
at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_73] Caused by: java.lang.IllegalStateException: Failed to resolve expression: oxf.run-mode
at org.jboss.metadata.property.DefaultExpressionReplacer.parseAndResolve(DefaultExpressionReplacer.java:232)
at org.jboss.metadata.property.DefaultExpressionReplacer.resolveExpressionStringRecursively(DefaultExpressionReplacer.java:92)
at org.jboss.metadata.property.DefaultExpressionReplacer.replaceProperties(DefaultExpressionReplacer.java:76)
at org.jboss.metadata.parser.util.MetaDataElementParser.getElementText(MetaDataElementParser.java:194)
at org.jboss.metadata.parser.ee.ParamValueMetaDataParser.parse(ParamValueMetaDataParser.java:78)
at org.jboss.metadata.parser.servlet.WebCommonMetaDataParser.parse(WebCommonMetaDataParser.java:70)
at org.jboss.metadata.parser.servlet.WebMetaDataParser.parse(WebMetaDataParser.java:175)
at org.jboss.metadata.parser.servlet.WebMetaDataParser.parse(WebMetaDataParser.java:55)
at org.jboss.as.web.deployment.WebParsingDeploymentProcessor.deploy(WebParsingDeploymentProcessor.java:91)
at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [jboss-as-server-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
```

It seems like JBoss tries to evaluate the expression `${oxf.run-mode}`, while it didn't previously. As a quick workaround, you can replace `${oxf.run-mode}` with a constant:

```xml
<param-value>prod</param-value>
```

**Comment by ebruchez** [comment]
Mmh, I think this would be only if somebody placed that expression in web.xml. Closing for now.
