### ISSUE TITLE
Support Liferay 7/DXP

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2843]
See [forum](http://discuss.orbeon.com/Liferay-7-exception-seems-not-supported-td4661640.html).

**Comment by ebruchez** [comment]
Information we got on Liferay DXP:

- relevant 6.2 portal features are still available in Liferay DXP
- biggest change is that Liferay is now based on OSGI
- development method is "changed drastically" but the legacy plugin SDK is still available with limited functionality
- DXP requires OSGI compatible custom module development (unclear what that means)
- doc is [here](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/introduction)

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/155e14e62e2b01d8)

**Comment by ebruchez** [comment]
First error obtained:

```
25-Aug-2016 23:54:51.073 SEVERE [http-nio-9090-exec-1] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet jsp threw exception
 java.lang.ClassNotFoundException: com.liferay.portal.util.PortalUtil cannot be found by proxy-portlet_7.0.2
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:394)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:357)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:349)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.orbeon.private.orbeon.oxf.portlet.liferay.FormRunnerAuthFilter$.amendRequestWithUser(FormRunnerAuthFilter.scala:97)
```

Suspecting this is due to the new OSGi modularization.

**Comment by ebruchez** [comment]
The doc mentions [breaking changes](https://dev.liferay.com/develop/reference/-/knowledge_base/7-0/breaking-changes) but doesn't say that `PortalUtil` is entirely gone. It should still be there.

**Comment by ebruchez** [comment]
Asking a question in the [Liferay forums](https://web.liferay.com/community/forums/-/message_boards/message/78165165).

**Comment by ebruchez** [comment]
Got an answer. It seems that `PortalUtil ` moved from:

    com.liferay.portal.util.PortalUtil

to:

    com.liferay.portal.kernel.util

So we need to:

- [ ] get the new API JAR
- [ ] figure out how to compile to one or another API depending on the Liferay version (or compile to both and access via an interface)

**Comment by ebruchez** [comment]
Also:

- `portal-service.jar` has been renamed `portal-kernel.jar `. See [Identifying Module Dependencies](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/adapting-to-liferay-7s-api-with-the-code-upgrade-tool#identifying-module-dependencies).
- `com.liferay.portal.model.User` has moved to `com.liferay.portal.kernel.model.User` in the same JAR

**Comment by ebruchez** [comment]
Hit another double issue. Liferay 7 exposes `window.define()`, which causes `nprogress.js` and `autosize.js` to use `define()` to define modules. This also means that these modules are not put in the global scope in that case.

I tried to use `require()` to access these modules, but to no avail. So for now I think we can modify both `nprogress.js` and `autosize.js` to disable calling `define()`.

**Comment by ebruchez** [comment]
Tasks:

- [x] get the new API JAR
- [ ] figure out how to compile to one or another API depending on the Liferay version (or compile to both and access via an interface)
- [ ] language dropdown doesn't work
- [ ] list and fix CSS issues
    - repeated grid menus are not in their cells
    - navbar icons look bad
    - repeated grid "+" looks bad
    - navbar is too tall
    - form area, navbar, buttons are not all aligned on the right
    - control labels appear blueish

**Comment by desi77** [comment]
Hello we would like to use orbeon with liferay 7. Is it possible now or work is still in progress? Any idea of a possible deliverable's date ? Thank you

**Comment by ebruchez** [comment]
@desi77 Some things might work with Orbeon Forms 2016.3 based on progress described above (2016.2 wouldn't work at all). We are aware that some components are broken and the look and feel needs adjustments. Feel free to try and report issues but please be aware that this is for now entirely unofficial.

The tentative plan is to release Liferay 7 support in [Orbeon Forms 2017.1](https://doc.orbeon.com/roadmap.html#orbeon-forms-20171) around April/May, but keep in mind that this plan can still change.

**Comment by fbonin** [comment]
Hi,
I see that you changed the date to 2017.2. 

Were there any progress in 2017.1? What is not ready in this release?

**Comment by ebruchez** [comment]
@fbonin All the items not checked [in this comment](https://github.com/orbeon/orbeon-forms/issues/2843#issuecomment-243288886) are still pending.

I fear that no progress has been made for 2017.1. What does your timeline look like? We still plan to complete this, it's just that there is no enough time left for 2017.1.

**Comment by fbonin** [comment]
Hi,
We wanted to migrate to Liferay 7 in the upcoming months. We don't have an official date but it was planned for the summer (it might change). We are only using the Form Runner portlet though.

**Comment by ebruchez** [comment]
@fbonin Good we are now planning to do this in June.

**Comment by ebruchez** [comment]
First JavaScript error I see now is "Cannot read property 'configure' of undefined", at `h.NProgress.configure`, where `h` is the global `Window`. So we have that NProgress issue already reported above.

**Comment by ebruchez** [comment]
Current appearance of Controls form.Needs fixing:

- [ ]  gray bar under title
- [ ] shadowed carets `<` `>` in wizard TOC and icons in buttons bar

![screen shot 2017-06-09 at 11 36 12 am](https://user-images.githubusercontent.com/105769/26989427-e6f156d4-4d07-11e7-920d-48adf3eca187.png)

**Comment by ebruchez** [comment]
Other JavaScript libraries which seem test for `typeof define === 'function'`:

- `imagesLoaded`
- `ladda`
- `spin` (part of `ladda`)
- `dragula`

**Comment by ebruchez** [comment]
This does something:

```javascript
require('nprogress.js', function (nprogress) {
    console.log('xxx');
    console.log(nprogress);
}, function (error) {
    console.log(error);
});
```

So `require` is asynchronous, and here causes the load of:

```xml
<script src="/combo/?browserId=other&amp;minifierType=&amp;languageId=en_US&amp;b=7002&amp;t=1496965026083&amp;nprogress.js"></script>
```

which is not found. So it doesn't look like `nprogress` registers itself, or we are not querying it properly.

**Comment by ebruchez** [comment]
Solution after discussion with @avernet: we simply backup and clear the global `define` and `exports` before loading our JavaScript files, and we restore them right after.

This is done by `XFormsResourceRewriter`, which only works right now when resources are combined. However, with embedding, only combined resources work anyway, so that is fine for now.

**Comment by ebruchez** [comment]
Confirming that this solution works.

**Comment by ebruchez** [comment]
So if all goes well, we are left with CSS issues, of which there are many.

**Comment by ebruchez** [comment]
Confirming that the language selector menu still doesn't work.

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#search/Liferay+june+12/15bd5395783d73be)

**Comment by ebruchez** [comment]
Moving tasks to the bottom::

- [x] get the new API JAR
- [x] figure out how to compile to one or another API depending on the Liferay version (or compile to both and access via an interface)
- [x] `SignaturePad` not defined: maybe same issue as `nprogress.js` and `autosize.js`?
  - would _really_ be nice if we could use `require()` in all 3 cases!
- [x] list and fix CSS issues
  - [x] repeated grid menus are not in their cells
  - [x] navbar icons look bad
  - [x] repeated grid "+" looks bad
  - [x] repeated grid border lines are doubled
  - [x] form area, navbar, buttons are not all aligned on the right
  - [x] control labels appear blueish
  - [x] navbar is too tall
  - [x] Wizard left/right arrows box is not centered
- [ ] check other builtin forms
- [ ] test out full portlet
- [ ] language dropdown doesn't work
- [ ] Signature is not scaled

**Comment by ebruchez** [comment]
Progressed on figuring out why navigation doesn't work. It turns out that Liferay 7 by default enables [Automatic single page applications](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/automatic-single-page-applications).

This explains why there is a difference when doing a force reload of the page, where it works, or not.

The easiest fix, for now, would be to disable SPA for our portlet. Later, we can enable it and make it work. See also:

- ~~Top-level listeners re-registered when script reloaded #3166~~
- Support Form Runner forms inclusion with jQuery.load() #1577
- Embedding: support page navigation #3141

**Comment by ebruchez** [comment]
See also [Single Page Applications with SennaJS and Liferay Faces](https://web.liferay.com/web/kyle.stiemann/blog/-/blogs/single-page-applications-with-sennajs-and-liferay-faces#fnref2) which says:

> This didn't seem to fit in the blog but Inácio Nery (https://github.com/inacionery) also added a nice feature that allows developers to specify how SennaJS will treat resources that they added to the <head> section. As alluded to above, Liferay 7 unloads/removes CSS resources from the <head> section on navigation, but it does not remove <script>s. This is great default functionality because CSS resources can be unloaded but scripts cannot. However Inácio Nery added the ability to change this functionality by allowing developers to customize the data-senna-track attribute of their <head> resources (https://github.com/liferay/liferay-portal/commit/870041f3434c559ea135dc76357992­10a004c194). If the developer does not specify a data-senna-track attribute, <script>s and CSS will default to the functionality mentioned above. However, if the developer wants to change this for certain resources, they need only add the data-senna-track attribute to override the default. For example, to ensure that CSS is not unloaded during SennaJS navigation, add data-senna-track="permanent" to your CSS element:
> 
> <link href="example/example.css" data-senna-track="permanent" />
> 
> <script>s are not unloaded/removed during navigation (meaning they default to data-senna-track="permanent"), but you can set them to be:
> 
> <script src="example/example.js" data-senna-track="temporary" />
> 
> A word of caution, this will not actually unload the objects created by the JS resource. Potentially, this could create duplicate objects and cause problems because SennaJS will not avoid loading a <script> multiple times as it does with data-senna-track="permanent" (the default for <script>s).
> 
> See the SennaJS docs for more details: http://sennajs.com/docs#trackableresources

**Comment by ebruchez** [comment]
Stack trace for `Node` issue with full portlet:

```
Caused by: java.lang.NoClassDefFoundError: org/w3c/dom/Node
	at org.orbeon.oxf.webapp.Orbeon$.initialize(Orbeon.scala:62)
	at org.orbeon.oxf.externalcontext.OrbeonWebApp$$anonfun$1.apply(WebAppContext.scala:120)
	at org.orbeon.oxf.externalcontext.OrbeonWebApp$$anonfun$1.apply(WebAppContext.scala:120)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at org.orbeon.oxf.externalcontext.ParametersAndAttributes$$anon$1.getOrElseUpdate(WebAppContext.scala:96)
	at org.orbeon.oxf.externalcontext.OrbeonWebApp$class.$init$(WebAppContext.scala:120)
	at org.orbeon.oxf.externalcontext.ServletWebAppContext.<init>(WebAppContext.scala:125)
	at org.orbeon.oxf.externalcontext.WebAppContext$.apply(WebAppContext.scala:170)
	at org.orbeon.oxf.pipeline.InitUtils$.runWithServletContext(InitUtils.scala:167)
	at org.orbeon.oxf.webapp.OrbeonServletContextListener$$anonfun$contextInitialized$1.apply$mcV$sp(OrbeonServletContextListener.scala:42)
	at org.orbeon.oxf.webapp.OrbeonServletContextListener$$anonfun$contextInitialized$1.apply(OrbeonServletContextListener.scala:42)
	at org.orbeon.oxf.webapp.OrbeonServletContextListener$$anonfun$contextInitialized$1.apply(OrbeonServletContextListener.scala:42)
	at org.orbeon.oxf.webapp.ServletPortlet$.withRootException(ServletPortlet.scala:104)
	at org.orbeon.oxf.webapp.OrbeonServletContextListener.contextInitialized(OrbeonServletContextListener.scala:41)
	at com.liferay.portal.kernel.servlet.SecurePluginContextListener.instantiatingListener(SecurePluginContextListener.java:355)
	at com.liferay.portal.kernel.servlet.SecurePluginContextListener.instantiatingListeners(SecurePluginContextListener.java:163)
	... 69 more
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.Node cannot be found by orbeon_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:444)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:357)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:349)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by ebruchez** [comment]
Stack trace if I disable the listener:

```
java.lang.NoClassDefFoundError: org/w3c/dom/Node
	at org.orbeon.oxf.webapp.Orbeon$.initialize(Orbeon.scala:62)
	at org.orbeon.oxf.externalcontext.OrbeonWebApp$$anonfun$1.apply(WebAppContext.scala:120)
	at org.orbeon.oxf.externalcontext.OrbeonWebApp$$anonfun$1.apply(WebAppContext.scala:120)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at org.orbeon.oxf.externalcontext.ParametersAndAttributes$$anon$1.getOrElseUpdate(WebAppContext.scala:96)
	at org.orbeon.oxf.externalcontext.OrbeonWebApp$class.$init$(WebAppContext.scala:120)
	at org.orbeon.oxf.externalcontext.ServletWebAppContext.<init>(WebAppContext.scala:125)
	at org.orbeon.oxf.externalcontext.WebAppContext$.apply(WebAppContext.scala:170)
	at org.orbeon.oxf.servlet.OrbeonServlet$$anonfun$init$1.apply$mcV$sp(OrbeonServlet.scala:59)
	at org.orbeon.oxf.servlet.OrbeonServlet$$anonfun$init$1.apply(OrbeonServlet.scala:59)
	at org.orbeon.oxf.servlet.OrbeonServlet$$anonfun$init$1.apply(OrbeonServlet.scala:59)
	at org.orbeon.oxf.webapp.ServletPortlet$.withRootException(ServletPortlet.scala:104)
	at org.orbeon.oxf.servlet.OrbeonServlet.init(OrbeonServlet.scala:58)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at com.liferay.portal.osgi.web.wab.extender.internal.adapter.ServletExceptionAdapter.init(ServletExceptionAdapter.java:56)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.init(EndpointRegistration.java:95)
	at org.eclipse.equinox.http.servlet.internal.context.ContextController.doAddServletRegistration(ContextController.java:575)
```

**Comment by ebruchez** [comment]
Similar error when removing servlets:

```
Caused by: java.lang.NoClassDefFoundError: org/w3c/dom/Node
	at org.orbeon.oxf.webapp.Orbeon$.initialize(Orbeon.scala:62)
	at org.orbeon.oxf.externalcontext.OrbeonWebApp$$anonfun$1.apply(WebAppContext.scala:120)
	at org.orbeon.oxf.externalcontext.OrbeonWebApp$$anonfun$1.apply(WebAppContext.scala:120)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at org.orbeon.oxf.externalcontext.ParametersAndAttributes$$anon$1.getOrElseUpdate(WebAppContext.scala:96)
	at org.orbeon.oxf.externalcontext.OrbeonWebApp$class.$init$(WebAppContext.scala:120)
	at org.orbeon.oxf.externalcontext.PortletWebAppContext.<init>(WebAppContext.scala:145)
	at org.orbeon.oxf.externalcontext.WebAppContext$.apply(WebAppContext.scala:171)
	at org.orbeon.oxf.portlet.OrbeonPortlet$$anonfun$init$1.apply$mcV$sp(OrbeonPortlet.scala:72)
	at org.orbeon.oxf.portlet.OrbeonPortlet$$anonfun$init$1.apply(OrbeonPortlet.scala:69)
	at org.orbeon.oxf.portlet.OrbeonPortlet$$anonfun$init$1.apply(OrbeonPortlet.scala:69)
	at org.orbeon.oxf.webapp.ServletPortlet$.withRootException(ServletPortlet.scala:104)
	at org.orbeon.oxf.portlet.OrbeonPortlet.init(OrbeonPortlet.scala:69)
	at javax.portlet.GenericPortlet.init(GenericPortlet.java:136)
```

**Comment by ebruchez** [comment]
If we cannot support the full portlet for 2017.1, that might be still ok, and we will have to document that.

**Comment by ebruchez** [comment]
Adding `xml-apis.jar` to `WEB-INF/lib` seems to go past this error. It's unclear yet whether we can/should bundle `xml-apis.jar`.

The next error is:

```
javax.servlet.ServletException: configuration file exist-conf.xml not found or not readable
	at org.exist.http.servlets.EXistServlet.init(EXistServlet.java:109)
	at com.liferay.portal.osgi.web.wab.extender.internal.adapter.ServletExceptionAdapter.init(ServletExceptionAdapter.java:56)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.init(EndpointRegistration.java:95)
```

**Comment by ebruchez** [comment]
Checking the logs, I see:

    EXistServlet: exist.home=null
    reading configuration from /Users/ebruchez/Orbeon/null/exist-conf.xml

This is computed from:

```java
String dbHome = config.getInitParameter("basedir");
dbHome =
    (dbHome == null) ?
    config.getServletContext().getRealPath(".") :
    config.getServletContext().getRealPath(dbHome);
```

So `config.getServletContext().getRealPath()`  always returns `null`, and this explains why things break. If that is the case, with our very old version of eXist, it doesn't seem like it is possible to start the servlet without modifications. So we can simply say that the embedded eXist is not supported in the full portlet

**Comment by ebruchez** [comment]
Next error: class `org.orbeon.oxf.portlet.liferay.FormRunnerAuthFilter$` is not found.

Commenting out the portlet filters takes us pass this error.

Then the landing page loads, but resources are not found. Setting this gets us past:

```xml
<property 
    as="xs:boolean" 
    name="oxf.url-rewriting.wsrp.encode-resources"         
    value="true"/>
```

Next error:

    org.apache.xerces.jaxp.SAXParserFactoryImpl cannot be cast to javax.xml.parsers.SAXParserFactory

```
|----------------------------------------------------------------------------------------------------------------------|
|Exception: java.lang.ClassCastException                                                                               |
|----------------------------------------------------------------------------------------------------------------------|
|javax.xml.parsers.SAXParserFactory                 |newInstance                   |                              |    |
|net.sf.ehcache.config.ConfigurationFactory         |parseConfiguration            |ConfigurationFactory.java     | 155|
|----------------------------------------------------------------------------------------------------------------------|
|Exception: net.sf.ehcache.CacheException                                                                              |
|----------------------------------------------------------------------------------------------------------------------|
|net.sf.ehcache.config.ConfigurationFactory         |parseConfiguration            |ConfigurationFactory.java     | 159|
|net.sf.ehcache.config.ConfigurationFactory         |parseConfiguration            |ConfigurationFactory.java     | 103|
|----------------------------------------------------------------------------------------------------------------------|
|Exception: net.sf.ehcache.CacheException                                                                              |
|----------------------------------------------------------------------------------------------------------------------|
|net.sf.ehcache.config.ConfigurationFactory         |parseConfiguration            |ConfigurationFactory.java     | 105|
|net.sf.ehcache.CacheManager                        |parseConfiguration            |CacheManager.java             | 680|
|net.sf.ehcache.CacheManager                        |init                          |CacheManager.java             | 369|
|net.sf.ehcache.CacheManager                        |<init>                        |CacheManager.java             | 317|
|org.orbeon.oxf.cache.Caches$Private$               |liftedTree1$1                 |Caches.scala                  |  45|
|----------------------------------------------------------------------------------------------------------------------|
|Exception: org.orbeon.oxf.common.OXFException                                                                         |
|----------------------------------------------------------------------------------------------------------------------|
|org.orbeon.oxf.cache.Caches$Private$               |liftedTree1$1                 |Caches.scala                  |  48|
```

**Comment by ebruchez** [comment]
We could possibly work around this by:

- using the `CacheManager(Configuration configuration)` constructor
- creating our `Configuration` via the Ehcache `BeanHandler` class

This doesn't explain why the cast fails though.

**Comment by ebruchez** [comment]
Entering separate issue #3264 for full portlet support.

**Comment by ebruchez** [comment]
Form Runner proxy portlet support is in. Separate issues cover possible full portlet support, as well as bugs and enhancements.
