### ISSUE TITLE
Explicitly close JDBC ResultSet and Statement

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2859]
We close `Connection`s, but it's been reported that JBoss warns about statements:

```
11:27:51,284 WARN  [org.jboss.jca.adapters.jdbc.WrappedConnection] (http-/0.0.0.0:8080-3) Closing a statement you left open, please do your own housekeeping: java.lang.Throwable: STACKTRACE
    at org.jboss.jca.adapters.jdbc.WrappedConnection.registerStatement(WrappedConnection.java:1677)
    at org.jboss.jca.adapters.jdbc.WrappedStatement.<init>(WrappedStatement.java:105)
    at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.<init>(WrappedPreparedStatement.java:69)
    at org.jboss.jca.adapters.jdbc.jdk6.WrappedPreparedStatementJDK6.<init>(WrappedPreparedStatementJDK6.java:52)
    at org.jboss.jca.adapters.jdbc.jdk6.WrappedConnectionJDK6.wrapPreparedStatement(WrappedConnectionJDK6.java:79)
    at org.jboss.jca.adapters.jdbc.WrappedConnection.prepareStatement(WrappedConnection.java:405)
    at org.orbeon.oxf.fr.relational.crud.Common$class.formVersion(Common.scala:46) [orbeon.jar:]
```

See also [this SO question](http://stackoverflow.com/questions/103938/resultset-not-closed-when-connection-closed).

[+1 from customer](https://mail.google.com/mail/u/0/#inbox/1560c2ee1235da5c)

**Comment by ebruchez** [comment]
It shouldn't be too hard to close `ResultSet`s and `Statement`s after use explicitly.

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/2789956/messages/55303931#comment_454304796) getting [ORA-01000: maximum open cursors exceeded](http://stackoverflow.com/questions/12192592/java-sql-sqlexception-ora-01000-maximum-open-cursors-exceeded)
