### ISSUE TITLE
Proxy portlet throws exception upon load

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3030]
With the latest build:

```
SEVERE: Servlet.service() for servlet orbeonformsproxyportlet Servlet threw exception
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.getHeaders$15efad69()Ljava/util/Enumeration;
	at org.orbeon.private.orbeon.oxf.fr.embedding.APISupport$$anonfun$requestHeaders$1.apply(APISupport.scala:1127)
	at org.orbeon.private.scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.orbeon.private.scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.orbeon.private.jcifs.netbios.SessionServicePacket.foreach(SessionServicePacket.java:23893)
	at org.orbeon.private.scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.orbeon.private.scala.collection.immutable.List.flatMap(List.scala:327)
```

Could this be an issue with Proguard? Maybe check just deploying the non-Proguarded version.

**Comment by ebruchez** [comment]
Copying all JAR files to `lib` doesn't show this error and the proxy portlet appears to work. Now the question is why did this start happening?

I tried reverting to Proguard 5.2.1. from 5.3.1, and also tried 5.3.2. Same apparent result.

**Comment by ebruchez** [comment]
There is an `jcifs.netbios` in the stacktrace. This seems wrong! We don't make use of `jcifs`.

- [ ] figure out which of our libraries depends on `jcifs` (maybe none?)

**Comment by ebruchez** [comment]
Well actually we uwe `jcifs` from `ApacheHttpClient` for `NTCredentials`.

**Comment by ebruchez** [comment]
Still, that shouldn't be in the stack trace at that point.

**Comment by ebruchez** [comment]
Tried removing the mapping of `jcifs` from our `jarjar` task. Getting similar error:

```
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.getHeaders$15efad69()Ljava/util/Enumeration;
	at org.orbeon.private.orbeon.oxf.fr.embedding.APISupport$$anonfun$requestHeaders$1.apply(APISupport.scala:1167)
	at org.orbeon.private.scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.orbeon.private.scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at jcifs.netbios.SessionServicePacket.foreach(SessionServicePacket.java:23893)
	at org.orbeon.private.scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
```

**Comment by ebruchez** [comment]
Removing entirely `jarjar` step:

```
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.getHeaders$15efad69()Ljava/util/Enumeration;
	at org.orbeon.oxf.fr.embedding.APISupport$$anonfun$requestHeaders$1.apply(APISupport.scala:1167)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at jcifs.netbios.SessionServicePacket.foreach(SessionServicePacket.java:23893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at org.orbeon.oxf.portlet.OrbeonProxyPortlet.org$orbeon$oxf$portlet$OrbeonProxyPortlet$$newRequestDetails(OrbeonProxyPortlet.scala:232)
```

**Comment by ebruchez** [comment]
Issue appears to stem from #3040.
