### ISSUE TITLE
ant clean produces java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3085]
Running `ant clean`, I get the following error. It still seems to do its job, but obviously should be fixed.

```
Buildfile: /Users/avernet/Drive/Work/Product/build.xml

init:
     [echo] Building Orbeon Forms 2017.1-SNAPSHOT.201701251753
     [echo] Using Ant Apache Ant(TM) version 1.9.4 compiled on April 29 2014

sbt-clean:
     [exec] [info] Loading global plugins from /Users/avernet/.sbt/0.13/plugins
     [exec] [info] Loading project definition from /Users/avernet/Drive/Work/Product/project
     [exec] [info] Set current project to root (in build file:/Users/avernet/Drive/Work/Product/)
     [exec] [info] Set current project to root (in build file:/Users/avernet/Drive/Work/Product/)
     [exec] java.lang.IllegalArgumentException: requirement failed: Source file '/Users/avernet/Drive/Work/Product/target/.history' does not exist.
     [exec]      at scala.Predef$.require(Predef.scala:233)
     [exec]      at sbt.IO$.copyFile(IO.scala:636)
     [exec]      at sbt.IO$.move(IO.scala:839)
     [exec]      at sbt.IO$$anonfun$move$1.apply(IO.scala:825)
     [exec]      at sbt.IO$$anonfun$move$1.apply(IO.scala:825)
     [exec]      at scala.Function$$anonfun$tupled$1.apply(Function.scala:77)
     [exec]      at scala.Function$$anonfun$tupled$1.apply(Function.scala:76)
     [exec]      at scala.collection.immutable.List.foreach(List.scala:318)
     [exec]      at sbt.IO$.move(IO.scala:825)
     [exec]      at sbt.Defaults$$anonfun$doClean$1.apply(Defaults.scala:748)
     [exec]      at sbt.Defaults$$anonfun$doClean$1.apply(Defaults.scala:745)
     [exec]      at sbt.IO$.withTemporaryDirectory(IO.scala:344)
     [exec]      at sbt.Defaults$.doClean(Defaults.scala:745)
     [exec]      at sbt.Defaults$$anonfun$projectTasks$3.apply(Defaults.scala:313)
     [exec]      at sbt.Defaults$$anonfun$projectTasks$3.apply(Defaults.scala:313)
     [exec]      at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
     [exec]      at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
     [exec]      at sbt.std.Transform$$anon$4.work(System.scala:63)
     [exec]      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
     [exec]      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
     [exec]      at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
     [exec]      at sbt.Execute.work(Execute.scala:237)
     [exec]      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
     [exec]      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
     [exec]      at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
     [exec]      at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
     [exec]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [exec]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]      at java.lang.Thread.run(Thread.java:745)
     [exec] [error] (xupdate/*:clean) java.lang.IllegalArgumentException: requirement failed: Source file '/Users/avernet/Drive/Work/Product/target/.history' does not exist.
     [exec] [error] Total time: 1 s, completed Jan 25, 2017 9:53:34 AM

BUILD FAILED
/Users/avernet/Drive/Work/Product/build.xml:90: exec returned: 1
```

**Comment by avernet** [comment]
[SBT's issue 2406](https://github.com/sbt/sbt/issues/2406) covers this. Adding `parallelExecution in Global := false`, as mentioned in a comment on that issue, solves the problem, but I'm not sure we want to do that.

The `historyPath in ThisBuild := Some((target in LocalRootProject).value / ".history")`, done [per the SBT documentation](http://www.scala-sbt.org/0.13/docs/Howto-Interactive-Mode.html#Use+the+same+history+for+all+projects), seems to be triggering this issue. Even if less desirable, placing the `.history` in the root directory is a way around this issue. So, for now, I'll go for this.

After updating, you might want to move your `ROOT/.target/.history` to `ROOT/.history`.

**Comment by avernet** [comment]
Not sure how, but I thought this fixed the issue, but then I'm having it again :(. So I'm reverting the change, and reopening this issue.
