### ISSUE TITLE
Liferay: PDF doesn't work

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3225]
Getting:

```
java.lang.IllegalArgumentException: application/pdf is an unsupported content type
	at com.liferay.portlet.MimeResponseImpl.setContentType(MimeResponseImpl.java:159)
	at org.orbeon.private.orbeon.oxf.portlet.BufferedPortlet$$anonfun$org$orbeon$oxf$portlet$BufferedPortlet$$writeResponseWithParameters$3.apply(BufferedPortlet.scala:1169)
	at org.orbeon.private.scala.Option.foreach(Option.scala:257)
	at enumeratum.EnumEntry.org$orbeon$oxf$portlet$BufferedPortlet$$writeResponseWithParameters(EnumEntry.scala:22169)
	at org.orbeon.oxf.portlet.OrbeonProxyPortlet$$anonfun$doView$1$$anonfun$apply$1.apply$mcV$sp(OrbeonProxyPortlet.scala:1099)
	at org.orbeon.oxf.portlet.OrbeonProxyPortlet$$anonfun$doView$1$$anonfun$apply$1.apply(OrbeonProxyPortlet.scala:2090)
	at org.orbeon.oxf.portlet.OrbeonProxyPortlet$.withRootException(OrbeonProxyPortlet.scala:318)
	at org.orbeon.oxf.portlet.OrbeonProxyPortlet$$anonfun$doView$1.apply(OrbeonProxyPortlet.scala:1090)
	at org.orbeon.private.scala.Option.foreach(Option.scala:257)
	at org.orbeon.oxf.portlet.OrbeonProxyPortlet.doView(OrbeonProxyPortlet.scala:89)
```

**Comment by ebruchez** [comment]
Before, we just had a GET of a resource URL, which worked.

Now, we do a `replace="all`'. This POSTs the HTML form, which is a portlet action URL. The result is that the resulting `application/pdf` content is set as the content of the portlet, and is rejected by the portal.

Could we instead do a POST to the same URL except as a resource URL? For that, we would need to have the resource URL at hand.

Could we just replace `p_p_lifecycle=1` with `p_p_lifecycle=2`?

**Comment by ebruchez** [comment]
We can't just do that. `/xforms-server-submit` on `<form>`:

```
http://localhost:9090/web/guest/orbeon-forms?
p_auth=POH59dFJ&
p_p_id=orbeonformsportlet_WAR_orbeon_INSTANCE_HPcSeyGuTRhz&
p_p_lifecycle=1&
p_p_state=normal&
p_p_mode=view&
p_p_col_id=column-1&
p_p_col_count=1&
_orbeonformsportlet_WAR_orbeon_INSTANCE_HPcSeyGuTRhz_orbeon.path=%2Fxforms-server-submit
```

`ORBEON.xforms.Globals.xformsServerURL["o0xforms-form"]`:

```
http://localhost:9090/web/guest/orbeon-forms?
p_p_id=orbeonformsportlet_WAR_orbeon_INSTANCE_HPcSeyGuTRhz
p_p_lifecycle=2
p_p_state=normal
p_p_mode=view
p_p_resource_id=%2Fxforms-server
p_p_cacheability=cacheLevelPage
p_p_col_id=column-1
p_p_col_count=1
_orbeonformsportlet_WAR_orbeon_INSTANCE_HPcSeyGuTRhz_orbeon.path=%2Ffr%2Forbeon%2Fcontrols%2Fnew
```

So if we do this, we should probably generate the submit URL each time.

**Comment by ebruchez** [comment]
One way:

- modify `xf:submission` to support an AVT on `f:url-type`
- set `f:url-type="resource"` when doing the `replace="all"` for the PDF
- first pass of two-pass submission must pass submission path with corresponding URL type

**Comment by ebruchez** [comment]
We shouldn't use `f:url-type="resource"` because that was meant to control how to resolve the submission URL. But we could change that to another attribute, like `xxf:response-url-type="resource"` which would only make sense for `replace="all".
