### ISSUE TITLE
Ant ant orbeon-dist, or any other ant orbeon commands, cannot run 'sbt'

### ISSUE THREAD

**Issue by langholloman** [orbeon/orbeon-forms#3593]
When following the directions at: https://doc.orbeon.com/contributors/building-orbeon-forms.html - sbt seems to go well when either running in command or through IntelliJ (I'm running on Windows 10). Ant build & plugins are available in IntelliJ, with the numerous 'orbeon' actions/commands displaying.

Using IntelliJ:
If I try to run orbeon-dist from the IntelliJ Ant build window, I get an alert noting : Cannot Run Ant: JKD(1.) needed to run this Ant target is not configured. Please update your settings in the Project Structure dialog. I have the settings set to the Java 8 JDK paths...does it absolutely need to be JDK 7?

Using command line:
If I change directories to the root orbeon-forms-master, then use command ant orbeon-dist, or just using ant....here's the following return noting it cannot run the program 'sbt'. Any ideas?

``
Buildfile: C:\...path...\orbeon-forms-master\build.xml

init:
     [echo] Building Orbeon Forms 2018.1-SNAPSHOT.201805162133
     [echo] Using Ant Apache Ant(TM) version 1.10.3 compiled on March 24 2018

prepare:

war-common:

BUILD FAILED
C:\...path...\orbeon-forms-master\build.xml:285: Execute failed: java.io.IOException: Cannot run program "sbt" (in directory "C:\...path...\orbeon-forms-master"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:631)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:498)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:448)
        at org.apache.tools.ant.Target.performTasks(Target.java:469)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1370)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:849)
        at org.apache.tools.ant.Main.startAnt(Main.java:228)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 23 more

Total time: 1 second``

**Comment by ebruchez** [comment]
Are you able to figure out how to fix it? We do not currently have a Windows setup to try this.

**Comment by langholloman** [comment]
I have been able to make some progress by making sure that various settings for Project Structure and File > Settings needs to have the current installed/active Java JDK...in this case 1.8. Now in Intellij, I don't get the: Cannot Run Ant: JKD(1.7) needed to run this Ant target is not configured. The Ant build error is still the "cannot run program "sbt";. Do I need to make any customizations to the build.xml for my build instance downloaded from the master source here on github?

**Comment by ebruchez** [comment]
Good that there is progress.

> Do I need to make any customizations to the build.xml for my build instance downloaded from the master source here on github?

Try putting an absolute path to the sbt command.

**Comment by langholloman** [comment]
are you referring to the Windows Environmental Variables for SBT_HOME, or is the location in the build.xml to put an absolute path?

**Comment by langholloman** [comment]
I set the following and made a little more progress :) <exec executable="C:\Program Files (x86)\sbt\bin\sbt.bat" failonerror="true">

run cmd: ant orbeon-dist, and this is what I get:
"C:\Program Files\Java\jdk1.8.0_172\bin\java.exe" -Xmx512m -Xss32m "-Dant.home=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant" "-Dant.library.dir=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib" -Dfile.encoding=UTF-8 -classpath "C:\dev\army\g8\orbeon-forms-master\lib\junit.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-antlr.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-apache-bcel.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-apache-bsf.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-apache-log4j.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-apache-oro.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-apache-regexp.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-apache-resolver.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-apache-xalan2.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-commons-logging.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-commons-net.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-jai.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-javamail.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-jdepend.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-jmf.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-jsch.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-junit.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-junit4.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-launcher.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-netrexx.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-swing.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant-testutil.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\ant\lib\ant.jar;C:\Program Files\Java\jdk1.8.0_172\lib\tools.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\lib\idea_rt.jar" com.intellij.rt.ant.execution.AntMain2 -logger com.intellij.rt.ant.execution.IdeaAntLogger2 -inputhandler com.intellij.rt.ant.execution.IdeaInputHandler -Dskip.compilation=true -buildfile C:\dev\army\g8\orbeon-forms-master\build.xml orbeon-dist
build.xml
init
Building Orbeon Forms 2018.1-SNAPSHOT.201805172011
Using Ant Apache Ant(TM) version 1.9.4 compiled on April 29 2014
prepare
war-common
[info] Loading global plugins from C:\Users\holloman.lang\.sbt\0.13\plugins
[info] Loading project definition from C:\dev\army\g8\orbeon-forms-master\project
[info] Resolving key references (13668 settings) ...
[info] Set current project to root (in build file:/C:/dev/army/g8/orbeon-forms-master/)
[error] Expected letter
[error] Expected symbol
[error] Expected '!'
[error] Expected '+'
[error] Expected '++'
[error] Expected '^'
[error] Expected '^^'
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected ';'
[error] Expected end of input.
[error] Expected 'early('
[error] Expected '-'
[error] Expected '--'
[error] Expected 'show'
[error] Expected 'all'
[error] Expected '*'
[error] Expected '{'
[error] Expected project ID
[error] Expected configuration
[error] Expected key
[error] 2018.1-SNAPSHOT.201805172011
[error] ^
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
C:\dev\army\g8\orbeon-forms-master\build.xml:285: exec returned: 1
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:643)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.Main.start(Main.java:198)
	at org.apache.tools.ant.Main.main(Main.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.ant.execution.AntMain2.main(AntMain2.java:30)
C:\dev\army\g8\orbeon-forms-master\build.xml:285: exec returned: 1
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:643)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.Main.start(Main.java:198)
	at org.apache.tools.ant.Main.main(Main.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.ant.execution.AntMain2.main(AntMain2.java:30)
C:\dev\army\g8\orbeon-forms-master\build.xml:285: exec returned: 1
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:643)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.Main.start(Main.java:198)
	at org.apache.tools.ant.Main.main(Main.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.ant.execution.AntMain2.main(AntMain2.java:30)

Ant build completed with 3 errors and 2 warnings in 25s at 5/17/2018 3:11 PM

**Comment by ebruchez** [comment]
Interesting. Could it be that it doesn't find the `build.sbt` file now?

**Comment by langholloman** [comment]
I set the failonerror="false", and it made it through:
init:
**prepare:
war-common:
exist-task:
exist-import-sample-data-to-build:
orbeon-dist-war:
proxy-portlet-jar:** _---- this is where it failed with an out of memory failure:_
**proxy-portlet-jar:**
 [proguard] ProGuard, version 5.3.1
 [proguard] Reading input...
 [proguard] Reading program directory [C:\orbeon-forms-master\orbeon-war\jvm\target\webapp\WEB-INF\lib] (filtered)
 [proguard] Reading library jar [C:\Program Files\Java\jdk1.8.0_172\jre\lib\rt.jar]
 [proguard] Reading library jar [C:\orbeon-forms-master\orbeon-war\jvm\target\webapp\WEB-INF\lib\slf4j-api-1.7.21.jar]
 [proguard] Reading library jar [C:\orbeon-forms-master\lib\provided\javax.servlet-api-3.0.1.jar]
 [proguard] Reading library jar [C:\orbeon-forms-master\lib\provided\portlet-api_2.0.jar]
 [proguard] Reading library jar [C:\orbeon-forms-master\lib\provided\liferay-portal-service-6.1.1.jar]
 [proguard] Reading library jar [C:\orbeon-forms-master\lib\provided\liferay-portal-kernel-7.0.jar]
 [proguard] Initializing...

**BUILD FAILED**
C:\orbeon-forms-master\build.xml:196: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at proguard.classfile.constant.Utf8Constant.getStringRepresentation(Utf8Constant.java:283)
        at proguard.classfile.constant.Utf8Constant.switchToStringRepresentation(Utf8Constant.java:174)
        at proguard.classfile.constant.Utf8Constant.getString(Utf8Constant.java:128)
        at proguard.classfile.ProgramClass.getString(ProgramClass.java:116)
        at proguard.classfile.constant.NameAndTypeConstant.getType(NameAndTypeConstant.java:104)
        at proguard.classfile.ProgramClass.getType(ProgramClass.java:164)
        at proguard.classfile.constant.RefConstant.getType(RefConstant.java:103)
        at proguard.classfile.util.ClassReferenceInitializer.visitAnyRefConstant(ClassReferenceInitializer.java:206)
        at proguard.classfile.util.SimplifiedVisitor.visitAnyMethodrefConstant(SimplifiedVisitor.java:193)
        at proguard.classfile.util.SimplifiedVisitor.visitMethodrefConstant(SimplifiedVisitor.java:205)
        at proguard.classfile.constant.MethodrefConstant.accept(MethodrefConstant.java:69)
        at proguard.classfile.ProgramClass.constantPoolEntriesAccept(ProgramClass.java:457)
        at proguard.classfile.util.ClassReferenceInitializer.visitProgramClass(ClassReferenceInitializer.java:100)
        at proguard.classfile.ProgramClass.accept(ProgramClass.java:358)
        at proguard.classfile.ClassPool.classesAccept(ClassPool.java:124)
        at proguard.Initializer.execute(Initializer.java:146)
        at proguard.ProGuard.initialize(ProGuard.java:233)
        at proguard.ProGuard.execute(ProGuard.java:98)
        at proguard.ant.ProGuardTask.execute(ProGuardTask.java:316)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:448)
        at org.apache.tools.ant.Target.performTasks(Target.java:469)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1370)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)

**Comment by ebruchez** [comment]
Since the `<proguard>` tasks runs out of memory, adding memory to `ant` might fix that too.

**Comment by langholloman** [comment]
I’ll give that a try and quit as many background processes as possible to
free up memory stability

**Comment by ebruchez** [comment]
Probably not current, closing.
