### ISSUE TITLE
java.lang.ClassCastException: class org.orbeon.private.apache.http.client.utils.URIUtils$UriFlag not an enum

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4604]
Happens when accessing `http://localhost:8080/orbeon-embedding/`, for the embedding war, which uses `API.embedFormJava()`.

```
java.lang.ClassCastException: class org.orbeon.private.apache.http.client.utils.URIUtils$UriFlag not an enum
	at java.util.EnumSet.noneOf(EnumSet.java:112)
	at org.orbeon.private.apache.http.client.utils.URIUtils.<clinit>(URIUtils.java:66)
	at org.orbeon.private.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:93)
	at org.orbeon.private.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.orbeon.private.orbeon.oxf.http.ApacheHttpClient.connect(ApacheHttpClient.scala:162)
	at org.orbeon.private.orbeon.oxf.fr.embedding.APISupport$Private$.connectURL(APISupport.scala:415)
	at org.orbeon.private.orbeon.oxf.fr.embedding.APISupport$.callService(APISupport.scala:206)
	at org.orbeon.private.orbeon.oxf.fr.embedding.APISupport$.proxyPage$2da46587(APISupport.scala:60)
	at org.orbeon.oxf.fr.embedding.servlet.API$.$anonfun$embedPageJava$2(API.scala:46)
	at org.orbeon.oxf.fr.embedding.servlet.API$.$anonfun$embedPageJava$2$adapted(API.scala:36)
	at org.orbeon.private.orbeon.oxf.fr.embedding.APISupport$.withSettings(APISupport.scala:267)
	at org.orbeon.oxf.fr.embedding.servlet.API$.embedPageJava(API.scala:36)
	at org.orbeon.oxf.fr.embedding.servlet.API$.embedFormJava(API.scala:68)
	at org.orbeon.oxf.fr.embedding.servlet.API.embedFormJava(API.scala)
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:253)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.orbeon.oxf.fr.embedding.servlet.ServletFilter.$anonfun$doFilter$2(ServletFilter.scala:127)
	at org.orbeon.private.scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.orbeon.private.orbeon.oxf.fr.embedding.APISupport$.scopeSettings(APISupport.scala:260)
	at org.orbeon.oxf.fr.embedding.servlet.ServletFilter.$anonfun$doFilter$1(ServletFilter.scala:118)
	at org.orbeon.oxf.fr.embedding.servlet.ServletFilter.$anonfun$doFilter$1$adapted(ServletFilter.scala:112)
	at org.orbeon.private.scala.Option.foreach(Option.scala:407)
	at org.orbeon.oxf.fr.embedding.servlet.ServletFilter.doFilter(ServletFilter.scala:112)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ebruchez** [comment]
- [ ] repro
- [ ] try disabling Proguard optimizations

**Comment by ebruchez** [comment]
- specifically allowed that `enum`
- also fixed issue related to deserialization of `BasicCookieStore`

Also upgraded to Proguard 6.2.2 along the way, but this was not was solved the issue.
