### ISSUE TITLE
Support Liferay 7.3

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4740]
Right now, we are getting:

```
java.lang.UnsupportedOperationException: Requires 3.0 opt-in
	at com.liferay.portlet.internal.PortletRequestImpl.getRenderParameters(PortletRequestImpl.java:523)
	at javax.portlet.filter.PortletRequestWrapper.getRenderParameters(PortletRequestWrapper.java:139)
	at org.orbeon.oxf.portlet.OrbeonProxyPortlet.pathParameterOpt$1(OrbeonProxyPortlet.scala:247)
```

However, we do have this in our `portlet.xml`:

```xml
<portlet-app version="3.0" xmlns="http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd">
```

[This link](https://help.liferay.com/hc/en-us/articles/360044149512-Portlet-3-0-API-Opt-In) shows:

```xml
<?xml version="1.0"?>

<portlet-app xmlns="http://xmlns.jcp.org/xml/ns/portlet"
			 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/portlet http://xmlns.jcp.org/xml/ns/portlet/portlet-app_3_0.xsd"
			 version="3.0">
	...
</portlet-app>
```

**Comment by ebruchez** [comment]
- [ ] try updating `portlet.xml` as shown above

**Comment by ebruchez** [comment]
We have at least one report of things working with Liferay 7.3 ([customer](https://3.basecamp.com/3600924/buckets/6794635/messages/3989106388#__recording_3996472473)).

**Comment by ebruchez** [comment]
Another [customer](https://3.basecamp.com/3600924/buckets/5422190/messages/4832008567#__recording_4837384210) reports that things are working.

**Comment by ebruchez** [comment]
- [ ] test with Liferay 7.3 on our end
