### ISSUE TITLE
When sessions are destroyed, we get: `java.lang.ClassCastException: class scala.Some cannot be cast to class org.orbeon.oxf.webapp.SessionListeners`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4830]
```
javax.servlet.ServletException: java.lang.ClassCastException: class scala.Some cannot be cast to class org.orbeon.oxf.webapp.SessionListeners (scala.Some and org.orbeon.oxf.webapp.SessionListeners are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @2ca65ce4)
	at org.orbeon.oxf.webapp.OrbeonSessionListener.$anonfun$sessionDestroyed$1(OrbeonSessionListener.scala:63)
	at org.orbeon.oxf.webapp.ServletPortlet$.withRootException(ServletPortlet.scala:108)
	at org.orbeon.oxf.webapp.OrbeonSessionListener.sessionDestroyed(OrbeonSessionListener.scala:63)
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:798)
	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:656)
	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:606)
	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:591)
	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5536)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1353)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1335)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class scala.Some cannot be cast to class org.orbeon.oxf.webapp.SessionListeners (scala.Some and org.orbeon.oxf.webapp.SessionListeners are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @2ca65ce4)
	at org.orbeon.oxf.webapp.OrbeonSessionListener$.sessionListenersDestroy(OrbeonSessionListener.scala:95)
	at org.orbeon.oxf.webapp.OrbeonSessionListener.$anonfun$sessionDestroyed$2(OrbeonSessionListener.scala:78)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.orbeon.oxf.webapp.ServletPortlet$.withRootException(ServletPortlet.scala:104)
	... 17 more
```

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/3672038267)

**Comment by avernet** [comment]
Regressed with #4766: we changed the code to use an `ExternalContext.Session`, instead of a plain `HttpSession`, but didn't account for the fact fact that with the former, `getAttribute()` returns an `Option`.
