### ISSUE TITLE
Support Tomcat 10+, WildFly 27+

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4885]
Exceptions when starting Tomcat:

```
java.lang.NoClassDefFoundError: javax/servlet/ServletContextListener
java.lang.NoClassDefFoundError: javax/servlet/http/HttpSessionListener
```

From the [Tomcat 10 migration guide](http://tomcat.apache.org/migration-10.html), under the heading "Servlet 5.0 API": "The Java package has changed from javax.servlet to jakarta.servlet.".

**Comment by avernet** [comment]
Even if for now customers wouldn't necessarily benefit from using Tomcat 10, they are likely to just use it, especially when installing a new system. So we should support Tomcat 10. And for a long while, other customers will still be using earlier versions. So we must continue to support Tomcat 9 and 8.5. And we wouldn't want to have 2 packages of Orbeon Forms depending on the version of Tomcat (or more precisely the Servlet API) used.

We have 25 source files importing classes from `javax.servlet`. Next, assuming there are no other major changes in Servlet 5 that impacts us:

- [ ] Determine way to use classes from either `javax.servlet` or `jakarta.servlet`, as needed.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/6462702/messages/5592928640)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/5837215338)

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/FMfcgzGrcjKRQtDpFSGLFqnkcpJRpHXz)

**Comment by ebruchez** [comment]
Relevant: https://github.com/apache/tomcat-jakartaee-migration

**Comment by avernet** [comment]
- Tomcat 10.0 implements Jakarta EE 9 / Jakarta Servlet 5.0
- Tomcat 10.1 implements Jakarta EE 10 / Jakarta Servlet 6.0
- WildFly 27 and 28 implement Jakarta EE 10 / Jakarta Servlet 6.0
- WildFly 26 is the last version to implement J2EE 8 / Java Servlet 4.0

[+1 from customer](https://3.basecamp.com/3600924/buckets/23878674/messages/6166276221)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1977270/messages/6706070675)

**Comment by avernet** [comment]
We would like to have a single war that can be deployed on both J2EE 8 / Java Servlet 4.0 and Jakarta EE 9+ / Jakarta Servlet 5.0+. The problem is that if we declare a `<servlet>` with a `<servlet-class>` in the `web.xml`, this class can't implement both `javax.servlet.HttpServlet` and `jakarta.servlet.HttpServlet`.

One way to deal with this is not to use `web.xml` to declare our servlet, but instead to use the Java Service Provider Interface (SPI) mechanism and have different implementations of `javax.servlet. ServletContainerInitializer` and `jakarta.servlet.ServletContainerInitializer`, which are referenced by the files `META-INF/services/javax.servlet.ServletContainerInitializer` and `META-INF/services/jakarta.servlet.ServletContainerInitializer`. Each implementation in its ([`onStartup`](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContainerInitializer.html)) gets a [`ServletContext`](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html) and can register the appropriate servlet (`addServlet`), listener (`addListener`), and filter (`addFilter`).

Now, we've never done this before, AFAIK, so we need to check if this actually works. If it does, then the rest, having our own implementation of a trait for the `javax` vs. `jakarta` (as done for `org.orbeon.oxf.externalcontext.ExternalContext.Request`) should be simple enough.

If this doesn't work, we may have to ship the war with a `web-javax.xml` and `web-jakarta.xml` and ask admins to rename the appropriate file to `web.xml` depending on the servlet container they are using.

**Comment by ebruchez** [comment]
Another avenue could be to use annotations.

**Comment by ebruchez** [comment]
Consider:

- using `trait`s to avoid code duplication
- all code using `javax.servlet` must be considered
- annotations might not help solve this problem
- it must still be possible to disable `LimiterFilter` without changing code (but web.xml is ok)

**Comment by obruchez** [comment]
- [ ] investigate exception at runtime in WildFly 26/27 (works in Tomcat 9/10)
- [ ] validate `context-param`/`init-param` naming for servlets/filters
- [ ] add mechanism to disable servlets/filters/listeners
- [ ] doc (feature, AuthorizerServlet, ServletFilter, embedPageJava, HttpLoggingFilter)
- [ ] discuss workaround for WildFly (datasources not available in `java:comp/env`)

**Comment by obruchez** [comment]
Here's the exception I encountered with WildFly (problem with `IOUtils.useAndClose`, `close()` on `ServletOutputStream` via structural type):

```
09:18:29,046 ERROR [io.undertow.request] (default task-4) UT005023: Exception handling request to /orbeon/xforms-server/b949a3bb71da298a8fd54437c4b1638f8466eb016e2417746bf08ae2f3a41554/orbeon-ecdde907a6271561aa57450ed09ad47e254ee591.js: java.lang.NoClassDefFoundError: jakarta/servlet/ServletOutputStream
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3328)
	at java.base/java.lang.Class.getMethod0(Class.java:3293)
	at java.base/java.lang.Class.getMethod(Class.java:2106)
	at deployment.orbeon.war//org.orbeon.io.IOUtils$.reflMethod$Method1(IOUtils.scala:66)
	at deployment.orbeon.war//org.orbeon.io.IOUtils$.$anonfun$useAndClose$1(IOUtils.scala:66)
	at deployment.orbeon.war//org.orbeon.io.IOUtils$.runQuietly(IOUtils.scala:71)
	at deployment.orbeon.war//org.orbeon.io.IOUtils$.useAndClose(IOUtils.scala:66)
	at deployment.orbeon.war//org.orbeon.oxf.xforms.processor.XFormsResourceRewriter$.generateAndClose(XFormsResourceRewriter.scala:47)
	at deployment.orbeon.war//org.orbeon.oxf.xforms.processor.XFormsAssetServer.serveCSSOrJavaScript(XFormsAssetServer.scala:325)
	at deployment.orbeon.war//org.orbeon.oxf.xforms.processor.XFormsAssetServer.start(XFormsAssetServer.scala:188)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor$4.run(PipelineProcessor.java:618)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor.executeChildren(PipelineProcessor.java:680)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor.start(PipelineProcessor.java:615)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.choose.ConcreteChooseProcessor.start(ConcreteChooseProcessor.java:230)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor$4.run(PipelineProcessor.java:618)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor.executeChildren(PipelineProcessor.java:680)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor.start(PipelineProcessor.java:615)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor$4.run(PipelineProcessor.java:618)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor.executeChildren(PipelineProcessor.java:680)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor.start(PipelineProcessor.java:615)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.choose.ConcreteChooseProcessor.start(ConcreteChooseProcessor.java:230)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor$4.run(PipelineProcessor.java:618)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor.executeChildren(PipelineProcessor.java:680)
	at deployment.orbeon.war//org.orbeon.oxf.processor.pipeline.PipelineProcessor.start(PipelineProcessor.java:615)
	at deployment.orbeon.war//org.orbeon.oxf.pipeline.InitUtils$.runProcessor(InitUtils.scala:81)
	at deployment.orbeon.war//org.orbeon.oxf.webapp.ProcessorService.$anonfun$service$1(ProcessorService.scala:47)
	at deployment.orbeon.war//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at deployment.orbeon.war//org.orbeon.oxf.logging.LifecycleLogger$.withEvent(LifecycleLogger.scala:80)
	at deployment.orbeon.war//org.orbeon.oxf.logging.LifecycleLogger$.withEventAssumingRequest(LifecycleLogger.scala:73)
	at deployment.orbeon.war//org.orbeon.oxf.webapp.ProcessorService.service(ProcessorService.scala:62)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.OrbeonServletImpl.$anonfun$service$3(OrbeonServlet.scala:94)
	at deployment.orbeon.war//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at deployment.orbeon.war//org.orbeon.oxf.webapp.ServletPortlet$.withRootException(ServletPortlet.scala:106)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.OrbeonServletImpl.$anonfun$service$1(OrbeonServlet.scala:85)
	at deployment.orbeon.war//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at deployment.orbeon.war//org.orbeon.oxf.util.DynamicVariable.withValue(DynamicVariable.scala:42)
	at deployment.orbeon.war//org.orbeon.oxf.webapp.ProcessorService$.withProcessorService(ProcessorService.scala:146)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.OrbeonServletImpl.service(OrbeonServlet.scala:85)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.JavaxHttpServlet.service(HttpServlet.scala:45)
	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.JavaxFilterChain.doFilter(FilterChain.scala:29)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.FormRunnerAuthFilterImpl.doFilter(FormRunnerAuthFilter.scala:72)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.JavaxFilter.doFilter(Filter.scala:29)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.JavaxFilterChain.doFilter(FilterChain.scala:29)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.LimiterFilterImpl.$anonfun$doFilter$4(LimiterFilter.scala:96)
	at deployment.orbeon.war//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at deployment.orbeon.war//org.orbeon.oxf.logging.LifecycleLogger$.withEvent(LifecycleLogger.scala:80)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.LimiterFilterImpl.$anonfun$doFilter$1(LimiterFilter.scala:96)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.LimiterFilterImpl.$anonfun$doFilter$1$adapted(LimiterFilter.scala:76)
	at deployment.orbeon.war//scala.Option.foreach(Option.scala:407)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.LimiterFilterImpl.doFilter(LimiterFilter.scala:76)
	at deployment.orbeon.war//org.orbeon.oxf.servlet.JavaxFilter.doFilter(Filter.scala:29)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.security.elytron-web.undertow-server@1.10.1.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68)
	at org.wildfly.security.elytron-base@1.18.1.Final//org.wildfly.security.auth.server.FlexibleIdentityAssociation.runAsFunctionEx(FlexibleIdentityAssociation.java:103)
	at org.wildfly.security.elytron-base@1.18.1.Final//org.wildfly.security.auth.server.Scoped.runAsFunctionEx(Scoped.java:161)
	at org.wildfly.security.elytron-base@1.18.1.Final//org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:73)
	at org.wildfly.security.elytron-web.undertow-server@1.10.1.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.handleRequest(ElytronRunAsHandler.java:67)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.2.14.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.core@2.2.14.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.core@2.2.14.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at org.wildfly.extension.undertow@26.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
	at io.undertow.core@2.2.14.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.core@2.2.14.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at org.jboss.xnio@3.8.5.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.ServletOutputStream from [Module "deployment.orbeon.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 107 more
```

That particular exception was with WildFly 26 (which doesn't use `jakarta.*`).

**Comment by obruchez** [comment]
@ebruchez: could you check commit [8322df2](https://github.com/orbeon/orbeon-forms/commit/8322df21ae8b44dee24d22ae3feae28af3740c4d), in particular the following files?

`src/main/resources/config/epilogue-servlet.xpl`
`xforms/jvm/src/main/resources/ops/xforms/xforms-renderer.xpl`

**Comment by ebruchez** [comment]
FYI @obruchez I restored the `getRealPath` on the `ServletContext`, which may or may not be useful for #5063.
