### ISSUE TITLE
`ClassCastException` on shutdown

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6074]
I am getting this with Tomcat 9 and Java 11.

```
Dec 13, 2023 12:15:38 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-nio-8080"]
Dec 13, 2023 12:15:38 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["https-jsse-nio-443"]
Dec 13, 2023 12:15:38 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service [Catalina]
Dec 13, 2023 12:15:38 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesObjectStreamClassCaches
WARNING: Failed to clear soft references from ObjectStreamClass$Caches for web application [embedding]
java.lang.ClassCastException: class java.io.ObjectStreamClass$Caches$1 cannot be cast to class java.util.Map (java.io.ObjectStreamClass$Caches$1 and java.util.Map are in module java.base of loader 'bootstrap')
        at org.apache.catalina.loader.WebappClassLoaderBase.clearCache(WebappClassLoaderBase.java:2268)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesObjectStreamClassCaches(WebappClassLoaderBase.java:2255)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1627)
        at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1555)
        at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:449)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5431)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:473)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:992)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.startup.Catalina.stop(Catalina.java:810)
        at org.apache.catalina.startup.Catalina$CatalinaShutdownHook.run(Catalina.java:933)

Dec 13, 2023 12:15:38 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesObjectStreamClassCaches
WARNING: Failed to clear soft references from ObjectStreamClass$Caches for web application [ROOT]
java.lang.ClassCastException: class java.io.ObjectStreamClass$Caches$1 cannot be cast to class java.util.Map (java.io.ObjectStreamClass$Caches$1 and java.util.Map are in module java.base of loader 'bootstrap')
        at org.apache.catalina.loader.WebappClassLoaderBase.clearCache(WebappClassLoaderBase.java:2268)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesObjectStreamClassCaches(WebappClassLoaderBase.java:2255)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1627)
        at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1555)
        at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:449)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5431)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:473)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:992)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.startup.Catalina.stop(Catalina.java:810)
        at org.apache.catalina.startup.Catalina$CatalinaShutdownHook.run(Catalina.java:933)

Dec 13, 2023 12:15:38 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesObjectStreamClassCaches
WARNING: Failed to clear soft references from ObjectStreamClass$Caches for web application [orbeon-servlet-embed]
java.lang.ClassCastException: class java.io.ObjectStreamClass$Caches$1 cannot be cast to class java.util.Map (java.io.ObjectStreamClass$Caches$1 and java.util.Map are in module java.base of loader 'bootstrap')
        at org.apache.catalina.loader.WebappClassLoaderBase.clearCache(WebappClassLoaderBase.java:2268)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesObjectStreamClassCaches(WebappClassLoaderBase.java:2255)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1627)
        at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1555)
        at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:449)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5431)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:473)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:992)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.startup.Catalina.stop(Catalina.java:810)
        at org.apache.catalina.startup.Catalina$CatalinaShutdownHook.run(Catalina.java:933)

Dec 13, 2023 12:15:38 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesObjectStreamClassCaches
WARNING: Failed to clear soft references from ObjectStreamClass$Caches for web application [orbeon]
java.lang.ClassCastException: class java.io.ObjectStreamClass$Caches$1 cannot be cast to class java.util.Map (java.io.ObjectStreamClass$Caches$1 and java.util.Map are in module java.base of loader 'bootstrap')
        at org.apache.catalina.loader.WebappClassLoaderBase.clearCache(WebappClassLoaderBase.java:2268)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesObjectStreamClassCaches(WebappClassLoaderBase.java:2255)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1627)
        at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1555)
        at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:449)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5431)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:473)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:992)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.startup.Catalina.stop(Catalina.java:810)
        at org.apache.catalina.startup.Catalina$CatalinaShutdownHook.run(Catalina.java:933)

Dec 13, 2023 12:15:38 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [orbeon] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@2655b3fa]) and a value of type [org.orbeon.saxon.sort.LRUCache] (value [org.orbeon.saxon.sort.LRUCache@7b4dcd49]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Dec 13, 2023 12:15:38 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesObjectStreamClassCaches
WARNING: Failed to clear soft references from ObjectStreamClass$Caches for web application [orbeon-ng]
java.lang.ClassCastException: class java.io.ObjectStreamClass$Caches$1 cannot be cast to class java.util.Map (java.io.ObjectStreamClass$Caches$1 and java.util.Map are in module java.base of loader 'bootstrap')
        at org.apache.catalina.loader.WebappClassLoaderBase.clearCache(WebappClassLoaderBase.java:2268)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesObjectStreamClassCaches(WebappClassLoaderBase.java:2255)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1627)
        at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1555)
        at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:449)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5431)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:473)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:992)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.startup.Catalina.stop(Catalina.java:810)
        at org.apache.catalina.startup.Catalina$CatalinaShutdownHook.run(Catalina.java:933)

Dec 13, 2023 12:15:38 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesObjectStreamClassCaches
WARNING: Failed to clear soft references from ObjectStreamClass$Caches for web application [hostapp]
java.lang.ClassCastException: class java.io.ObjectStreamClass$Caches$1 cannot be cast to class java.util.Map (java.io.ObjectStreamClass$Caches$1 and java.util.Map are in module java.base of loader 'bootstrap')
        at org.apache.catalina.loader.WebappClassLoaderBase.clearCache(WebappClassLoaderBase.java:2268)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesObjectStreamClassCaches(WebappClassLoaderBase.java:2255)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1627)
        at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1555)
        at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:449)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5431)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1389)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:976)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:473)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:992)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
        at org.apache.catalina.startup.Catalina.stop(Catalina.java:810)
        at org.apache.catalina.startup.Catalina$CatalinaShutdownHook.run(Catalina.java:933)

Dec 13, 2023 12:15:38 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-nio-8080"]
Dec 13, 2023 12:15:38 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["https-jsse-nio-443"]
Dec 13, 2023 12:15:38 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-nio-8080"]
Dec 13, 2023 12:15:38 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["https-jsse-nio-443"]
```

**Comment by avernet** [comment]
- The same happens with Java 17
- Those errors are not due to leftover files in the `$CATALINA_BASE/temp`

**Comment by ebruchez** [comment]
`ThreadLocal` messages might be the same as #182.

**Comment by avernet** [comment]
Removed "`ThreadLocal` not removed errors" from the title of this issue, since that part is already covered by #182.
