### ISSUE TITLE
NPE with `JavaxServletRegistration.addMapping()`

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6123]
If you have an older `web.xml` which keeps the old-style filters/servlets, `ServletRegistration.apply()` is passed `null` and you get an NPE. It would be nice to log the problem instead. Or should we use/obtain the existing servlet registration in this case (`getServletRegistration()`) and issue a warning?

![image](https://github.com/orbeon/orbeon-forms/assets/105769/895b5723-78de-4177-a835-a5d306eb9076)

**Comment by obruchez** [comment]
We now don't call `addMapping` and `addMappingForUrlPatterns` with `null` values in `*ServletContainerInitializer` and log errors instead.

**Comment by obruchez** [comment]
The servlet now starts, but fails with the following exception:

```
10:46:13.897 [main] ERROR org.orbeon.properties -
java.lang.AssertionError: assertion failed: ResourceManagerWrapper not initialized
	at scala.Predef$.assert(Predef.scala:223) ~[scala-library.jar:?]
	at org.orbeon.oxf.resources.ResourceManagerWrapper$.instance$lzycompute(ResourceManagerWrapper.scala:56) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.resources.ResourceManagerWrapper$.instance(ResourceManagerWrapper.scala:55) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.resources.ResourceManagerWrapper.instance(ResourceManagerWrapper.scala) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.processor.generator.URLGenerator$OXFResourceHandler.getValidity(URLGenerator.java:884) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.processor.generator.URLGenerator$1.getHandlerValidity(URLGenerator.java:747) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.processor.generator.URLGenerator$1.getValidityImpl(URLGenerator.java:678) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.processor.impl.ProcessorOutputImpl$TopLevelOutputFilter.getValidity(ProcessorOutputImpl.java:263) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.processor.impl.ProcessorOutputImpl.getValidity(ProcessorOutputImpl.java:420) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.processor.ProcessorImpl.getInputValidity(ProcessorImpl.java:499) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.processor.ProcessorImpl.getInputKeyValidity(ProcessorImpl.java:530) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.processor.ProcessorImpl.readCacheInputAsObject(ProcessorImpl.java:356) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.processor.ProcessorImpl.readCacheInputAsOrbeonDom(ProcessorImpl.java:318) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.processor.DOMSerializer.runGetDocument(DOMSerializer.scala:49) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.properties.Properties.$anonfun$update$1(Properties.scala:118) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.properties.Properties.$anonfun$update$1$adapted(Properties.scala:104) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.pipeline.InitUtils$.withPipelineContext(InitUtils.scala:50) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.properties.Properties.org$orbeon$oxf$properties$Properties$$update(Properties.scala:104) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.properties.Properties$.$anonfun$instance$1(Properties.scala:64) ~[orbeon-core.jar:2022.1-SNAPSHOT]
	at scala.Option.getOrElse(Option.scala:189) [scala-library.jar:?]
	at org.orbeon.oxf.properties.Properties$.instance(Properties.scala:62) [orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.cache.CacheSupport$.provider$lzycompute(CacheSupport.scala:55) [orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.cache.CacheSupport$.provider(CacheSupport.scala:54) [orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.cache.CacheSupport$.close(CacheSupport.scala:62) [orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.cache.ShutdownListenerImpl.contextDestroyed(ShutdownListener.scala:13) [orbeon-core.jar:2022.1-SNAPSHOT]
	at org.orbeon.oxf.servlet.JavaxServletContextListener.contextDestroyed(ServletContextListener.scala:23) [orbeon-servlet-support.jar:2022.1-SNAPSHOT]
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4540) [catalina.jar:9.0.74]
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5179) [catalina.jar:9.0.74]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257) [catalina.jar:9.0.74]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:187) [catalina.jar:9.0.74]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) [catalina.jar:9.0.74]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) [catalina.jar:9.0.74]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.74]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) [?:?]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:871) [catalina.jar:9.0.74]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:795) [catalina.jar:9.0.74]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.74]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) [catalina.jar:9.0.74]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) [catalina.jar:9.0.74]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.74]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) [?:?]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:871) [catalina.jar:9.0.74]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:249) [catalina.jar:9.0.74]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.74]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428) [catalina.jar:9.0.74]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.74]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:917) [catalina.jar:9.0.74]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.74]
	at org.apache.catalina.startup.Catalina.start(Catalina.java:772) [catalina.jar:9.0.74]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347) [bootstrap.jar:9.0.74]
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478) [bootstrap.jar:9.0.74]
```

**Comment by obruchez** [comment]
The servlets, filters, and listeners now load with the old `web.xml` configuration.

**Comment by obruchez** [comment]
- [ ] Document how the dynamic servlet container initializer can be disabled
