### ISSUE TITLE
Error starting proxy portlet with Liferay 7.4.3.106 CE GA106 

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6141]
Might also happen with other Liferay versions:

```
osgi/war/proxy-portlet.war?Bundle-SymbolicName=proxy-portlet&Web-ContextPath=/proxy-portlet&fileExtension=war&protocol=file
org.osgi.framework.BundleException: Error loading bundle activator.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:713) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:995) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:352) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.Module.doStart(Module.java:581) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.Module.start(Module.java:449) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:426) ~[org.eclipse.osgi.jar:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1148) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1181) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1038) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:238) [bundleFile:?]
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.osgi.Activator,org.apache.logging.log4j.util.Activator cannot be found by proxy-portlet_7.4.3.106
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:404) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:754) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:708) ~[org.eclipse.osgi.jar:?]
	... 9 more
```

**Comment by ebruchez** [comment]
As workaround, the log4j JAR files can be removed.
