### ISSUE TITLE
No need for explicit destroyForm before embedForm in Angular/React components

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#6257]
Following #6195, we don't need to explicitly call `destroyForm` before `embedForm` in both the Angular and React components.

**Comment by obruchez** [comment]
We seem to get an uncaught exception from time to time:

```
Uncaught java.lang.IllegalArgumentException: form `o5xforms-form` not found
    at $c_Lorg_orbeon_xforms_Page$.getXFormsFormFromNamespacedIdOrThrow__T__Lorg_orbeon_xforms_Form (http://localhost:8080/orbeon/xforms-server/baseline.js?updates=fr:58339:48)
    at http://localhost:8080/orbeon/xforms-server/baseline.js?updates=fr:53874:43
    at $c_sjsr_AnonFunction0.apply__O (http://localhost:8080/orbeon/xforms-server/baseline.js?updates=fr:81974:43)
    at http://localhost:8080/orbeon/xforms-server/baseline.js?updates=fr:65504:12
    at timer (http://localhost:4200/polyfills.js:1982:27)
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:320:171)
    at _Zone.runTask (http://localhost:4200/polyfills.js:137:37)
    at invokeTask (http://localhost:4200/polyfills.js:391:26)
    at ZoneTask.invoke (http://localhost:4200/polyfills.js:380:38)
    at data.args.<computed> (http://localhost:4200/polyfills.js:1964:26)
```

**Comment by obruchez** [comment]
It happens most of (all?) the times when doing the following sequence:

- embedForm(A)
- embedForm(B)
- embedForm(A)

**Comment by obruchez** [comment]
Actually, this seems to happen after embedding any form after orbeon/controls.

**Comment by obruchez** [comment]
Will track the uncaught exception problem in another issue.

**Comment by obruchez** [comment]
Decision: keep the extra/explicit `destroyForm` in the components as long as released versions of Orbeon Forms 2022 and 2023 need it.
