### ISSUE TITLE
IllegalArgumentException thrown after embedding a form after orbeon/controls

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#6258]
If we embed a form (any form?) after orbeon/controls has been embedded, we get the following exception:

```
Uncaught java.lang.IllegalArgumentException: form `o5xforms-form` not found
    at $c_Lorg_orbeon_xforms_Page$.getXFormsFormFromNamespacedIdOrThrow__T__Lorg_orbeon_xforms_Form (http://localhost:8080/orbeon/xforms-server/baseline.js?updates=fr:58339:48)
    at http://localhost:8080/orbeon/xforms-server/baseline.js?updates=fr:53874:43
    at $c_sjsr_AnonFunction0.apply__O (http://localhost:8080/orbeon/xforms-server/baseline.js?updates=fr:81974:43)
    at http://localhost:8080/orbeon/xforms-server/baseline.js?updates=fr:65504:12
    at timer (http://localhost:4200/polyfills.js:1982:27)
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:320:171)
    at _Zone.runTask (http://localhost:4200/polyfills.js:137:37)
    at invokeTask (http://localhost:4200/polyfills.js:391:26)
    at ZoneTask.invoke (http://localhost:4200/polyfills.js:380:38)
    at data.args.<computed> (http://localhost:4200/polyfills.js:1964:26)
```

**Comment by obruchez** [comment]
Can't reproduce this with or without the explicit call to `destroyForm` in the Angular/React components. Maybe the exception was caused by a "dirty" build?
